//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSapp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StockTbl
    {   [Key]
        public int StockID { get; set; }
        public string Ticker { get; set; }
        [Display(Name = "Date")]
        //[Required(ErrorMessage = "Please enter a start date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> StockDate { get; set; }
        public string OpeningPrice { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public string ClosingPrice { get; set; }
        public string AdjustedClosing { get; set; }
        public string Volume { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> TradeId { get; set; }
    }
}
